name: Eclipse JDT-Core BVS Experiment

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/experiment-eclipse-jdt-core.yml"

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/ribafish/eclipse.jdt.core.git"
  BRANCH: "feature/develocity"
  ARGS: "-Dscan.tag.gk-eclipse-exp"

jobs:
  Experiment:
    strategy:
      fail-fast: false
      matrix:
        goals:
          - "install -DskipTests=true -Dscan.tag.skipTests"
          - "install --batch-mode -f org.eclipse.jdt.core.compiler.batch -DlocalEcjVersion=99.99"
          - "verify --batch-mode --fail-at-end -Ptest-on-javase-21 -Pbree-libs -Papi-check -Djava.io.tmpdir=$WORKSPACE/tmp -Dproject.build.sourceEncoding=UTF-8 -Dtycho.surefire.argLine='--add-modules ALL-SYSTEM -Dcompliance=1.8,11,17,20 -Djdt.performance.asserts=disabled' -DlocalEcjVersion=99.99"
          - "verify -Dscan.tag.justVerify"
          - "verify --batch-mode --fail-at-end -Ptest-on-javase-21 -Pbree-libs -Papi-check -Dscan.value.profiles='test-on-javase-21,bree-libs,api-check'"
          - "verify --fail-never -Dscan.tag.failNever --batch-mode -Ptest-on-javase-21 -Pbree-libs -Papi-check -Dscan.value.profiles='test-on-javase-21,bree-libs,api-check'"
        experiment: [ 01-validate-local-build-caching-same-location, 02-validate-local-build-caching-different-locations ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDKs â˜•
        uses: actions/setup-java@v4
        with:
          java-version: |
            8
            17
            21
          mvn-toolchain-id: |
            JavaSE-1.8
            JavaSE-17
            JavaSE-21
          distribution: 'temurin'

      - name: Download the latest version of the validation scripts
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/download@actions-stable
        with:
          downloadDevelopmentRelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Xvfb and run experiment ${{ matrix.experiment }}
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        shell: bash
        working-directory: develocity-maven-build-validation
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          ./${{ matrix.experiment }}.sh -r ${{ env.GIT_REPO }} -g "${{ matrix.goals }}" -a "${{ env.ARGS }}" -s ${{ env.DEVELOCITY_URL }} -b ${{ env.BRANCH }}

      - name: Read summary from file and set GitHub Actions Summary
        shell: bash
        if: always()
        run: cat develocity-maven-build-validation/.data/${{ matrix.experiment }}/latest/*.receipt >> $GITHUB_STEP_SUMMARY
